### ISSUE TITLE
No report is being generated

### ISSUE THREAD

**Issue by jakobsack** [Customatics/leaptest-plugin#1]
Hi,

I've created a jenkins job as described in https://leaptest.com/support/learning-center/jenkins-integration . The test runs fine but the report is not being generated. 
The console output of the job looks like this:

```
Started by user Jakob Sack
Building remotely on xxx in workspace d:\workspace\xxx\Miscellaneous\Leaptest
Schedule: xxx | Schedule Id: 4e3ea8bd-745a-4f96-8c50-e65b5cc95cbd | Launched: SUCCESSFULLY
Case: AddQualification | Status: Passed | Elapsed: 00:01:09.2479432
ERROR: The system cannot find the path specified
Leaptest for Jenkins  plugin  successfully finished!
Build step 'Leaptest Integration' changed build result to SUCCESS
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Finished: FAILURE
```

I'm using Leaptest plugin 1.1.0 with Jenkins 2.56 on Windows 7.

**Comment by romanchetto** [comment]
Hi, @jakobsack 

To create a report file plugin uses JENKINS_HOME global variable. Unfortunately, Windows 7 can't find it. So, you has to add JENKINS_HOME to System environment variables. The value of that variable is your path to Jenkins folder like on the picture below.

![untitled](https://cloud.githubusercontent.com/assets/22563434/25476505/0ea363ac-2b43-11e7-8995-1ffba34d1f83.jpg)

**Comment by jakobsack** [comment]
Hi @romanchetto , thank you for the tip. Unfortunately it did not work as expected.
The problem is that our setup is not exactly the default setup. On master the installation is in `C:\Program Files (x86)\Jenkins`, but the worspaces are in `D:\buildroot`. On the slave where the leaptest job is being executed the slave resides in `D:\`and the workspace in `D:\workspace`.
I only set the environment variable on the slave to `D:\`.

**Comment by Sunderfield** [comment]
Is it not better to change the line at https://github.com/Customatics/leaptest-plugin/blob/1dece275d77f32f619f756fd82657b4f284d0405/src/main/java/com/customatics/leaptest_plugin/LeaptestJenkinsBridgeBuilder.java#L448 to use the environment variable for the current workspace? That would be dynamic.

**Comment by romanchetto** [comment]
@Sunderfield , You suggest using custom environment variable (JENKINS_WORKSPACE for example), don't you?

**Comment by Sunderfield** [comment]
I know that in a build, several environment variables exist under $env.
While I do not know for certain that those work inside of a plugin (I am
trying to build it now for testing) the variable $env.WORKSPACE has the
absolute path to the current workspace. (so the master in the master and
the slave specific folder in the slave.)

**Comment by romanchetto** [comment]
@Sunderfield,
I've added 
 ```
<jenkins.workspace>${env.WORKSPACE}</jenkins.workspace>
```
 to the pom.xml, and try to get it 
```
listener.getLogger().println(junitReportPath);
listener.getLogger().println(System.getProperty("jenkins.workspace"));
```
but the result is
![new picture](https://cloud.githubusercontent.com/assets/22563434/25532721/f5e744ce-2c36-11e7-88f5-f990fcc026da.jpg)

**Comment by Sunderfield** [comment]
I am having the same problem with getting the current build environment
variables to show up. I need to spend some more time on this next Monday.

**Comment by romanchetto** [comment]
Hi, @jakobsack , @Sunderfield 
I've uploaded version 1.0.1, where a special field for an external workspace path was added. I think, that's a good temporary solution, until the problem with env.WORKSPACE variable will be solved.
@jakobsack, Enter D:\workspace in this field and return JENKINS_HOME its default value, becouse changing that variable may occur troubles with another plugins. 

If your workspace has default path, DO NOT enter anything to that field!

To update plugin, go to Jenkins Plugin Manager, choose hpi file to download and restart Jenkins.

![new picture](https://cloud.githubusercontent.com/assets/22563434/25544795/ca085b76-2c64-11e7-930a-aa5b122ef148.jpg)

**Comment by jakobsack** [comment]
Hi @romanchetto and @Sunderfield ,

I tried the new version of the plugin. For me it does not work as expected but at least I can give you more information.
As already said we have several jenkins slaves, Leaptest is forced to run on a specific one.

```
| Computer | Jenkins home                   | Workspace    |
|----------|--------------------------------|--------------|
| master   | C:\Program Files (x86)\Jenkins | D:\buildroot |
| slave    | D:\                            | D:\workspace |
```

Since the job is set to be run on a specific slave I have set "workspace" to "D:\workspace".

After I created some folders manually I found out that the plugin now creates a report, but not under `slave:d:\workspace\xxx\Miscellaneous\Leaptest`, but under `master:d:\workspace\Leaptest`. That behaviour is wrong in two ways:
1) the report is generated on the wrong computer
2) the location of the report does not reflect the folder structure in jenkins

Here is the full log of the run:
```
Started by user Jakob Sack
Building remotely on yyy in workspace d:\workspace\xxx\Miscellaneous\Leaptest
D:\workspace\Leaptest\report.xml
Schedule: xxx | Schedule Id: 4e3ea8bd-745a-4f96-8c50-e65b5cc95cbd | Launched: SUCCESSFULLY
Case: AddQualification | Status: Passed | Elapsed: 00:01:33.5499609
Leaptest for Jenkins  plugin  successfully finished!
Build step 'Leaptest Integration' changed build result to SUCCESS
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Finished: FAILURE
```

**Comment by romanchetto** [comment]
Hi, @jakobsack

This is the code that is used for creation a JUnit report file

``` 
        String junitReportPath = null;
        if (StringUtils.isNotEmpty(getExternalWorkspacePath()) || !"".equals(getExternalWorkspacePath()))
        {
            junitReportPath = new File( String.format("%1$s\\%2$s\\%3$s",  getExternalWorkspacePath(), workspace.getName(),report)).getPath();
        }
        else
        {
            junitReportPath = new File( String.format("%1$s\\workspace\\%2$s\\%3$s",  System.getenv("JENKINS_HOME"),workspace.getName(),report)).getPath();
        }

        listener.getLogger().println(junitReportPath);
```

So, as you can see, by default, report file is created in default Jenkins workspace:
JENKINS_HOME\workspace\JOB_NAME\report.xml
C:\Program Files(x86)\Jenkins\workspace\Leaptest\report.xml in your case.

But if you enter a path to an external workspace, it is:
PATH_YOU_HAVE_ENTERED\JOB_NAME\report.xml
You need  D:\workspace\xxx\Miscellaneous\Leaptest\report.xml

So, @jakobsack, try to enter d:\workspace\xxx\Miscellaneous in "External workspace path" field.
And please, send me your workspace parameters, like on the screenshot below:
![new picture](https://cloud.githubusercontent.com/assets/22563434/25564276/6fdcff6c-2db8-11e7-976a-977367190544.jpg)

On Tuesday, I'll try to fix this problem with env.WORKSPACE and make it work.

**Comment by jakobsack** [comment]
Hi,

with two adjustments it does work now:
1) I forced the tests to run on master and set the full folder directory 
2) I set the external workspace path to "D:\buildroot\xxx\Miscellaneous"

Here is the screenshot @romanchetto requested:
![2017-05-02 10_20_00-configure system jenkins](https://cloud.githubusercontent.com/assets/776911/25609984/b9b8b29c-2f21-11e7-8368-b798ce09102d.jpg)

On the slave node it looks like this:
![2017-05-02 10_21_11-](https://cloud.githubusercontent.com/assets/776911/25609987/bbf96362-2f21-11e7-9f0e-5fe5153ed6cc.jpg)

To make the plugin even more robust I recommend you to run it in a subfolder:
![image](https://cloud.githubusercontent.com/assets/776911/25610185/8861b2d8-2f22-11e7-8231-72ff4bfc3219.png)

Thanks for your help so far!

**Comment by romanchetto** [comment]
Hi, @jakobsack , @Sunderfield !
Finally, I've solved this problem! I've added this:
```
EnvVars env = build.getEnvironment(listener);
String junitReportPath = String.format("%1$s\\%2$s",env.get("WORKSPACE"),report);
```
Now, I'm preparing version 1.0.2.
jakobsack , test it on your slave, please.

**Comment by jakobsack** [comment]
Hi @romanchetto , sorry for the late answer. It now works fine on master, but when executing the test on a slave it cannot create the report.

**Comment by romanchetto** [comment]
Hi, @jakobsack , I suppose if you change your remote root directory in slave configuration to "${WORKSPACE}" (without quotes), that may work.
