### ISSUE TITLE
Changing the report file name does not work - keeps reloading default

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#10]

**Comment by bicschneider** [comment]
Status?

**Comment by romanchetto** [comment]
Hello @bicschneider , I've just test it in 3.1.0 and has not succeeded to reproduce your problem
![picture3](https://user-images.githubusercontent.com/22563434/53172231-e19e0500-35f5-11e9-8cf5-6fa579764cc2.PNG)
![picture4](https://user-images.githubusercontent.com/22563434/53172251-eb276d00-35f5-11e9-8545-00739ae87858.PNG)

**Comment by bicschneider** [comment]
Thanks. In the futures please link your commit to the issue that you fixes, so we have transparency and traceability.
You can close it..
