### ISSUE TITLE
Extend the plugin to utilize variables on /api/v3/schedules/{scheduleId}/runNow extension point

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#13]
Utilizing the option could enable usage of same schedule on different sites etc..

![image](https://user-images.githubusercontent.com/3347017/48006718-5cf6ac00-e116-11e8-916b-df46ae93145c.png)

**Comment by romanchetto** [comment]
Hello @bicschneider ,
Thank you for your advice. This request is possible to use any number of key-value variables, so we will think how to implement it in the plugin the future release

**Comment by bicschneider** [comment]
To make it simple. Just specify a variable ala EnvInject plugin
```
var=${value-from-variable}
var2=value
```

**Comment by romanchetto** [comment]
Hello @bicschneider , var1 and var2 in swagger are just like an example. You can use any variable name. Need some specifying mechanism to detect variables for the plugin and for corresponding schedule, used in plugin

**Comment by bicschneider** [comment]
One option: you should have a list of Build Variables that should be parsed to the `runNow` ala 
New option in LeapWork plugin
```
Parse variables to 'run': "var1, var2"
```

**Comment by romanchetto** [comment]
Hello @bicschneider. In 3.1.1 "Schedule variables" field was added. More info in Readme. Let's continue discussing futher development of schedule variables for the plugin in #20 or in a new issue under [FEATURE-REQ] tag.
