### ISSUE TITLE
Emphasize in UI when schedules are "disabled", but still make it check-able for configuration

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#14]
Current version the "checkbox" is disabled but 
a) it is hard to see if all schedules are disabled and cannot be clicked
b) It is not possible to preconfigure Jenkins prior to enabling it in LeapWork.

![image](https://user-images.githubusercontent.com/3347017/48011601-6a189880-e120-11e8-8378-9a8d66a4695a.png)

**Comment by romanchetto** [comment]
Hello @bicschneider ,
Thank you for your advice. Implemented in 3.0.1
