### ISSUE TITLE
[3.0.0] Add "wait" until schedule is ready for running

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#16]
The new LeapWork does not have a "queue"-ing mechanism. The "plugin" will fail as the returned "runID" does not exist..

It makes the setup more resilient in the a-sync Jenkins setup

**Comment by bicschneider** [comment]
The new LeapWork does not have a "queue"-ing mechanism. The "plugin" will fail as the returned "runID" does not exist.. 

It makes the setup more resilient in the a-sync Jenkins setup

**Comment by romanchetto** [comment]
Hello @bicschneider ,
Time delay parameter does it, just increase its value up to 10 secs, for example.
API method returns RunId, and then schedule is starting to prepare. While it is preparing for adding to queue, run of this schedule does not exist. So, making API request during this small period of time will return 404. Leapwork team has told me, that they will fix this in future release

**Comment by bicschneider** [comment]
I will still make the implementation robust, rather than fail in some occasions. Is there a target for leapWork to release a robust handling?
