### ISSUE TITLE
[3.0.0] Show more detailed information about Errors and/or invalid schedules

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#19]
see #18 for configuration
```
14:27:00 2018-11-16T13:27:00.4447994+00:00 - Case is passed.
14:27:00 Environment: Azure agent
14:27:00 Schedule: XXX
14:27:01 There were detected 'ERRORS' or 'INVALID SCHEDULES' hence set the build status='FAILURE'
14:27:01 Leapwork for Jenkins  plugin  successfully finished!
14:27:01 Build step 'Leapwork Integration' changed build result to FAILURE
```

**Comment by romanchetto** [comment]
Hello @bicschneider 
Thank you for your advice, implemented in 3.0.1.

**Comment by romanchetto** [comment]
Hello @bicschneider 
Thank you for your advice, implemented in 3.0.1. but invalid schedules information printing was left in the end. May be it worth adding special boolean, which stops plugin execution if any invalid schedule exists

**Comment by bicschneider** [comment]
I agree - it is "too late" as of current implementation. As LeapWork cannot use HTTPS there should be an option to copy/paste in schedule ID (and / or) titles

**Comment by romanchetto** [comment]
Hello @bicschneider, Could you please be more specific about this option?

**Comment by bicschneider** [comment]
Enable "copy-paste" of the schedule id and names in stead of query the LeapWork controller.

**Comment by romanchetto** [comment]
Hello @bicschneider , Now you can copy-paste schedule names in 3.1.1. We decided not to allow do this with "Schedule ids" field.
