### ISSUE TITLE
Plugin 'fails' when the connection to leaptest machine is not stable

### ISSUE THREAD

**Issue by Sunderfield** [Customatics/leaptest-plugin#2]
I get the following error when the plugin throws an error while fetching a status from the leaptest machine. 
```
Schedule: LeaptestSeleniumSchedule | Schedule Id: 9d04b802-a232-48b5-a17a-d54ca3afe5ee | Launched: SUCCESSFULLY

ERROR: Code: 500 Status: Internal Server Error!
ERROR: Tried to get LeaptestSeleniumSchedule[9d04b802-a232-48b5-a17a-d54ca3afe5ee] state! Check connection to your server and try again!
INVALID SCHEDULES:
9d04b802-a232-48b5-a17a-d54ca3afe5ee
Leaptest for Jenkins  plugin  successfully finished!
```

**Comment by romanchetto** [comment]
Hi, @Sunderfield 
I'm not sure that this is unstable connecton.
This is the example of unstable connection:
![new picture](https://cloud.githubusercontent.com/assets/22563434/25618579/2ffc52d2-2f50-11e7-8c4c-e89374845bd6.jpg)

It looks like there are problems with leaptest controller.
Also, send me please Leaptest version you use, I'll check

**Comment by Sunderfield** [comment]
I have never had this with an earlyer version. I will try to roll back to the previous one and see if that fixes the problem.

**Comment by romanchetto** [comment]
@Sunderfield , 
I don't have such a problem. Could you, please, send me JSON response from your server
http://{leaptest_server_name}:9000/api/v1/runSchedules/state/9d04b802-a232-48b5-a17a-d54ca3afe5ee

**Comment by Sunderfield** [comment]
The reproduction is hard for this problem, I have now installed a fresh
version of the precious stable version. I will come back to you about my
findings.

**Comment by Sunderfield** [comment]
That did not fix my problem. I will roll back to the most recent stable.

**Comment by romanchetto** [comment]
@Sunderfield, You've faced with the error, that passed my tests. I am 95% sure that there is something wrong in your schedule state, and plugin can't read it correctly. I badly need to investigate it, so I need the JSON report from this request: 
http://{leaptest_server_name}:9010/api/v1/runSchedules/state/9d04b802-a232-48b5-a17a-d54ca3afe5ee
Please, send it to me. You'll help me make plugin more stable and better.

**Comment by Sunderfield** [comment]
It took some time before i got any personal data from the file. 
[scheduleState.zip](https://github.com/Customatics/leaptest-plugin/files/970840/scheduleState.zip)

**Comment by romanchetto** [comment]
Hi, @Sunderfield , I've checked that JSON and it is OK.
So, We need to check Leaptest API:
Open new tab in your browser and enter this inserting your server name (your port is 9010?):
http://{your_server_name}:9010/help/index#!/RunSchedules/RunSchedules_GetScheduleState
You'll get this:
![new picture](https://cloud.githubusercontent.com/assets/22563434/25627404/25640f84-2f6b-11e7-87b1-03262db3aca0.jpg)

Insert your schedule id and press try it out. You'll get all information from your server, including server code

![new picture](https://cloud.githubusercontent.com/assets/22563434/25627566/a91c5872-2f6b-11e7-9075-de73fc694bda.jpg)
Send me screenshots of results you'll get, please.

Also, it would be very helpful, if you send your LEAPTEST/Assets folder without any videos to my e-mail roman.syrych@customatics.com

**Comment by Sunderfield** [comment]
![image](https://cloud.githubusercontent.com/assets/6259835/25655229/838b7168-2ff4-11e7-8182-9262e679bef3.png)
I have added the screenshot, sending the assets will take more time as this will ask for quite some modifications to remove the urls, passwords etc,

**Comment by romanchetto** [comment]
@Sunderfield , could you please update plugin to version 1.0.3 and check if the problem still exists

**Comment by Sunderfield** [comment]
I have not seen the problem untill now, Will trigger a few more builds  in the next 3 hours to see if it returns or not.

**Comment by Sunderfield** [comment]
The problem occurred again. 
```
Schedule: LeaptestSeleniumSchedule | Schedule Id: 9d04b802-a232-48b5-a17a-d54ca3afe5ee | Launched: SUCCESSFULLY
ERROR: Code: 500 Status: Internal Server Error!
ERROR: Tried to get LeaptestSeleniumSchedule[9d04b802-a232-48b5-a17a-d54ca3afe5ee] state! Check connection to your server and try again!
Case: Regio - Create | Status: Passed | Elapsed: 00:00:16.6853547
Case: Regio - Delete | Status: Passed | Elapsed: 00:00:45.1016235
Case: Regio - Edit | Status: Done | Elapsed: 00:00:28.4233647
Case: Object - Create | Status: Passed | Elapsed: 00:00:29.0568999
Case: Object - Edit | Status: Failed | Elapsed: 00:01:39.4778135
.... more cases. 
Case: Login - Logout | Status: Passed | Elapsed: 00:00:16.5918160
Case: Login - Forgot password | Status: Passed | Elapsed: 00:00:09.8605667
INVALID SCHEDULES
9d04b802-a232-48b5-a17a-d54ca3afe5ee
Leaptest for Jenkins  plugin  successfully finished!
```

**Comment by romanchetto** [comment]
Hi, @Sunderfield ,
Do you have this error only with this schedule, or with all schedules you run, even with the simpliest cases like "Start - > Failed" or "Start -> Passed"?
If it occurs only with this schedule, could you please send this schedule with automation runs to leaptest support?

**Comment by Sunderfield** [comment]
This is the only schedule I run. I have created 3 in total  but those two
are not called for in the plugin.

**Comment by romanchetto** [comment]
@Sunderfield , Could you please run all your schedules using plugin? You can create a simple schedule with simple cases like "Start - > Failed" or "Start -> Passed". I just need to understand If any schedule fails using plugin, or only this one. That will help me understand if the problem in the plugin or in the Leaptest controller. In the end, send me plugin and leaptest logs of these schedules, please.

**Comment by romanchetto** [comment]
Hi @Sunderfield !
Finally I've understood what happens with your schedule!
This is your logs

```
Schedule: LeaptestSeleniumSchedule | Schedule Id: 9d04b802-a232-48b5-a17a-d54ca3afe5ee | Launched: SUCCESSFULLY
ERROR: Code: 500 Status: Internal Server Error!
ERROR: Tried to get LeaptestSeleniumSchedule[9d04b802-a232-48b5-a17a-d54ca3afe5ee] state! Check connection to your server and try again!
Case: Regio - Create | Status: Passed | Elapsed: 00:00:16.6853547
Case: Regio - Delete | Status: Passed | Elapsed: 00:00:45.1016235
Case: Regio - Edit | Status: Done | Elapsed: 00:00:28.4233647
Case: Object - Create | Status: Passed | Elapsed: 00:00:29.0568999
Case: Object - Edit | Status: Failed | Elapsed: 00:01:39.4778135
.... more cases. 
Case: Login - Logout | Status: Passed | Elapsed: 00:00:16.5918160
Case: Login - Forgot password | Status: Passed | Elapsed: 00:00:09.8605667
INVALID SCHEDULES
9d04b802-a232-48b5-a17a-d54ca3afe5ee
Leaptest for Jenkins  plugin  successfully finished!
```

Look:
The plugin uses Time Delay parameter (in advanced build parameters). By default it is 1 second, if you don't enter your value. This parameter is required to ask a schedule state after the schedule has been run. So you run a schedule, the plugin waits for 1 second by default and asks your controller for the schedule state. Sometimes Leaptest controller manages to create your schedule state and error does not occur. But if it hasn't created the state yet or another problem occured and it returns 500 error code.  That's why you "had a great run for the past few days without errors but now it's back".
Plugin uses such boolean variable as  ``scheduleIsStillRunning``. Its default value is ``true``. While it is ``true``, the plugin will be trying to get the schedule state. And I see in your logs information about cases. It means that the second attempt of getting the schedule state was successfull. But because of 500 error the plugin throws an exception and your schedule has become invalid for the plugin.  In this exception I've forgotten to set ``scheduleIsStillRunning`` variable to ``false``. That's why the plugin makes one more attempt to get the schedule state.

SOLUTION:
I'll change the default time delay value to 3 seconds and add ``scheduleIsStillRunning.setValue(false);`` to Exception handler. You can enter the value you want in build parameters, but I recommend 3 or more seconds. I'm going to upload new version of plugin 1.0.4 today. I hope it will help you.

**Comment by Sunderfield** [comment]
Testing with the plugin now. Thank you!
