### ISSUE TITLE
The default timeout is not visible for the user.. Move it to the UI as defaults

### ISSUE THREAD

**Issue by bicschneider** [Customatics/leaptest-plugin#4]

**Comment by bicschneider** [comment]
Status?

**Comment by romanchetto** [comment]
Hello @bicschneider , Could you provide more details please? 
When you create new build step, default time out is shown.
![picture5](https://user-images.githubusercontent.com/22563434/53172541-a0f2bb80-35f6-11e9-8c79-05f665442918.PNG)

**Comment by bicschneider** [comment]
Good..
